import { NextRequest, NextResponse } from 'next/server'

interface LineItem {
  code: string
  description: string
  billedAmount: number
  status: string
  issue: string | null
  fairPrice: number
  savings: number
  severity: string
  regulation: string
}

interface DisputeRequest {
  provider: string
  dateOfService: string
  billType: string
  lineItems: LineItem[]
  totalBilled: number
  totalFairPrice: number
  totalSavings: number
  patientName?: string
  accountNumber?: string
}

function generateDisputeLetter(data: DisputeRequest): string {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const flaggedItems = data.lineItems.filter((item) => item.status !== 'ok')
  const patientName = data.patientName || '[YOUR NAME]'
  const accountNumber = data.accountNumber || '[ACCOUNT NUMBER]'

  let itemDetails = ''
  flaggedItems.forEach((item, idx) => {
    itemDetails += `
${idx + 1}. ${item.code} — ${item.description}
   Billed Amount: $${item.billedAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
   Issue: ${item.issue || item.status}
   Fair Market Price: $${item.fairPrice.toLocaleString('en-US', { minimumFractionDigits: 2 })}
   Overcharge: $${item.savings.toLocaleString('en-US', { minimumFractionDigits: 2 })}
   Regulation: ${item.regulation}
`
  })

  return `${today}

${patientName}
${accountNumber}

${data.provider}
Billing Department
[PROVIDER ADDRESS]

RE: FORMAL DISPUTE — Date of Service: ${data.dateOfService}
    Total Billed: $${data.totalBilled.toLocaleString('en-US', { minimumFractionDigits: 2 })}
    Disputed Amount: $${data.totalSavings.toLocaleString('en-US', { minimumFractionDigits: 2 })}

To Whom It May Concern:

I am writing to formally dispute charges on my medical bill for services rendered on ${data.dateOfService}. After careful review of my itemized statement, I have identified ${flaggedItems.length} charge(s) that appear to contain billing errors, overcharges, or regulatory violations totaling $${data.totalSavings.toLocaleString('en-US', { minimumFractionDigits: 2 })}.

I am requesting an immediate review and correction of the following charges:

DISPUTED CHARGES:
${itemDetails}

TOTAL DISPUTED: $${data.totalSavings.toLocaleString('en-US', { minimumFractionDigits: 2 })} of $${data.totalBilled.toLocaleString('en-US', { minimumFractionDigits: 2 })} billed

LEGAL BASIS FOR THIS DISPUTE:

Under the No Surprises Act (effective January 1, 2022), patients are protected from surprise billing and balance billing for emergency services and certain non-emergency services at in-network facilities. Under the Hospital Price Transparency Rule (45 CFR Part 180), hospitals are required to make their standard charges publicly available.

Pursuant to the Fair Debt Collection Practices Act (15 USC §1692g), I request that you:

1. Provide a fully itemized bill with all CPT, HCPCS, and revenue codes
2. Provide the chargemaster rate for each service
3. Provide the Medicare-allowable amount for each service
4. Cease all collection activity on the disputed portion until this matter is resolved

Under the Fair Credit Reporting Act, you are prohibited from reporting this disputed amount to credit bureaus while the dispute is pending.

REQUESTED RESOLUTION:

I request that you adjust my bill to reflect fair market rates for the services actually provided. Based on my analysis, the corrected total should be approximately $${data.totalFairPrice.toLocaleString('en-US', { minimumFractionDigits: 2 })}.

If you believe these charges are correct, please provide written documentation supporting each charge within 30 days, including:
- Medical records justifying the level of service billed
- Comparison to Medicare fee schedule rates
- Explanation for any charges that exceed 200% of the Medicare rate

I expect a written response within 30 business days. If I do not receive a satisfactory response, I will file complaints with:
- My state Attorney General's office
- The Centers for Medicare & Medicaid Services (CMS)
- My state Department of Insurance
- The Consumer Financial Protection Bureau (CFPB)

Please direct all correspondence regarding this dispute to the address listed above.

Sincerely,

${patientName}

---
This dispute letter was generated by BillGuard (billguard.app)
Analysis powered by AI medical billing audit technology.
This letter is for informational purposes and does not constitute legal advice.
`
}

export async function POST(request: NextRequest) {
  try {
    const data: DisputeRequest = await request.json()

    const letter = generateDisputeLetter(data)

    return NextResponse.json({ letter })
  } catch (err) {
    console.error('Dispute letter error:', err)
    return NextResponse.json(
      { error: 'Failed to generate dispute letter' },
      { status: 500 }
    )
  }
}
